;******************************************************
;  CASSE-BRIQUE ASSETS
;------------------------------------------------------
;  Librairie des images de CASSE-BRIQUE
;  v 1.1  William LIN & Timoté VANNIER 20 Jan 2023
;******************************************************

;==== exported variables ====
extrn strt1:word
extrn strt2:word
extrn quit:word
extrn quit2:word
extrn img_menu_arrow:word
extrn img_menu_arrow_cover:word
extrn img_ball:word
extrn img_brick:word
extrn img_bar:word
extrn img_bar_cover:word
;=============================